package com.locallab.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * Represents an embedding model configuration for vector embeddings in RAG operations.
 *
 * <p>An EmbeddingModel stores the metadata required to use an Ollama embedding model for generating
 * vector representations of text. The vector dimensions are stored to ensure compatibility with the
 * vector store (Chroma).
 *
 * <h3>Example Usage:</h3>
 *
 * <pre>
 * EmbeddingModel model = new EmbeddingModel();
 * model.setName("Nomic Embed Text");
 * model.setOllamaModelName("nomic-embed-text");
 * model.setDimensions(768);
 * </pre>
 *
 * <h3>Entity Relationships:</h3>
 *
 * <p>This is a <strong>lookup entity</strong> - it does not maintain a collection of
 * ExperimentRuns. ExperimentRun references EmbeddingModel via {@code @ManyToOne} (unidirectional
 * from ExperimentRun side).
 *
 * @see com.locallab.model.ExperimentRun
 */
@Data
@Entity
@Table(name = "embedding_models")
public class EmbeddingModel {

    /** Unique identifier for the embedding model. Auto-generated by the database upon creation. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Display name for the embedding model. Must be unique to prevent duplicate configurations.
     *
     * <p>Example: {@code "Nomic Embed Text"}
     */
    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name must not exceed 100 characters")
    @Column(nullable = false, unique = true, length = 100)
    private String name;

    /**
     * The Ollama model name used for API calls. This is the identifier passed to Ollama's embedding
     * endpoint.
     *
     * <p>Example: {@code "nomic-embed-text"}
     */
    @NotBlank(message = "Ollama model name is required")
    @Size(max = 100, message = "Ollama model name must not exceed 100 characters")
    @Column(nullable = false, length = 100)
    private String ollamaModelName;

    /**
     * The number of dimensions in the embedding vectors produced by this model. This must match the
     * configuration in the vector store for compatibility.
     *
     * <p>Common values: 384, 768, 1024, 1536
     */
    @NotNull(message = "Dimensions is required")
    @Column(nullable = false)
    private Integer dimensions;
}
