package com.locallab.model;

import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;

import com.locallab.model.enums.RunStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a single execution run within an experiment.
 *
 * <p>An ExperimentRun captures the results of executing a specific model with specific
 * configuration parameters. Each run belongs to exactly one {@link Experiment} and records all
 * relevant metrics and outputs.
 *
 * <h3>Example Usage:</h3>
 *
 * <pre>
 * ExperimentRun run = ExperimentRun.builder()
 *     .experiment(experiment)
 *     .modelName("qwen2.5-coder:7b")
 *     .iteration(1)
 *     .status(RunStatus.PENDING)
 *     .build();
 * </pre>
 *
 * <h3>Entity Relationships:</h3>
 *
 * <ul>
 *   <li><strong>ManyToOne to Experiment:</strong> Each run belongs to exactly one Experiment
 *       (required). The relationship is lazy-loaded.
 *   <li><strong>ManyToOne to EmbeddingModel:</strong> Each run may optionally reference an
 *       EmbeddingModel for RAG operations.
 *   <li><strong>ManyToOne to SystemPrompt:</strong> Each run may optionally reference a
 *       SystemPrompt.
 * </ul>
 *
 * @see Experiment
 * @see EmbeddingModel
 * @see SystemPrompt
 * @see RunStatus
 */
@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "experiment_runs")
public class ExperimentRun {

    /**
     * Unique identifier for the experiment run.
     *
     * <p>Auto-generated by the database upon creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The experiment this run belongs to.
     *
     * <p>This relationship is required - every run must belong to an experiment.
     */
    @NotNull(message = "Experiment is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "experiment_id", nullable = false)
    private Experiment experiment;

    /**
     * The name of the Ollama model used for this run.
     *
     * <p>Example: {@code "qwen2.5-coder:7b"}
     */
    @NotBlank(message = "Model name is required")
    @Size(max = 100, message = "Model name must not exceed 100 characters")
    @Column(nullable = false, length = 100)
    private String modelName;

    /**
     * The embedding model used for RAG operations, if applicable.
     *
     * <p>Optional - only populated for runs that use retrieval-augmented generation.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "embedding_model_id")
    private EmbeddingModel embeddingModel;

    /**
     * The system prompt used for this run, if applicable.
     *
     * <p>Optional - runs may be executed without a system prompt.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "system_prompt_id")
    private SystemPrompt systemPrompt;

    /**
     * The iteration number within the experiment.
     *
     * <p>Used to identify runs when multiple iterations are configured. Iterations are 1-indexed.
     */
    @NotNull(message = "Iteration is required")
    @Column(nullable = false)
    private Integer iteration;

    /**
     * JSON configuration string containing the exact parameters used for this run.
     *
     * <p>Stores the hyperparameters and other settings applied during execution.
     */
    @Lob
    @Column(columnDefinition = "CLOB")
    private String config;

    /**
     * Current status of the run.
     *
     * <p>Tracks the run lifecycle: PENDING -> RUNNING -> SUCCESS/FAILED. Defaults to PENDING.
     *
     * @see RunStatus
     */
    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private RunStatus status = RunStatus.PENDING;

    /**
     * The complete output generated by the model.
     *
     * <p>Stored as a LOB to support lengthy responses. Populated upon successful completion.
     */
    @Lob
    @Column(columnDefinition = "CLOB")
    private String output;

    /**
     * Total generation time in milliseconds.
     *
     * <p>Measures the complete time from request submission to final token generation.
     */
    @Column private Long durationMs;

    /**
     * Throughput metric: tokens generated per second.
     *
     * <p>Calculated as total tokens divided by generation duration.
     */
    @Column private Double tokensPerSecond;

    /**
     * Time to first token in milliseconds.
     *
     * <p>Measures latency from request submission to the first token being generated.
     */
    @Column private Long timeToFirstTokenMs;

    /**
     * JSON string containing retrieved document chunks for RAG runs.
     *
     * <p>Stores chunk content, IDs, and relevance scores as JSON. Only populated for RAG runs.
     */
    @Lob
    @Column(columnDefinition = "CLOB")
    private String retrievedChunks;

    /**
     * Error message if the run failed.
     *
     * <p>Contains details about what went wrong during execution. Only populated when status is
     * FAILED.
     */
    @Lob
    @Column(columnDefinition = "CLOB")
    private String errorMessage;

    /**
     * Timestamp when this run was created/executed.
     *
     * <p>Automatically set by Hibernate on entity creation.
     */
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime timestamp;
}
