package com.locallab.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a reusable task template that defines a prompt structure for experiments.
 *
 * <p>A TaskTemplate is the foundational building block for experiments. It contains a prompt
 * template with optional {@code {{variable}}} placeholders that can be filled in at runtime.
 * Templates can be reused across multiple experiments, enabling consistent testing methodology.
 *
 * <h3>Example Usage:</h3>
 *
 * <pre>
 * TaskTemplate template = TaskTemplate.builder()
 *     .name("Code Review Task")
 *     .description("Review code for best practices and potential issues")
 *     .promptTemplate("Review the following code:\n\n{{code}}\n\nProvide feedback on...")
 *     .tags("code,review,quality")
 *     .evaluationNotes("Look for correctness, style, and performance")
 *     .build();
 * </pre>
 *
 * <h3>Entity Relationships:</h3>
 *
 * <ul>
 *   <li><strong>OneToMany to Experiment:</strong> A TaskTemplate can be referenced by many
 *       Experiments. Deleting a TaskTemplate will cascade delete all associated Experiments.
 * </ul>
 *
 * <h3>Variable Syntax:</h3>
 *
 * <p>The {@code promptTemplate} field supports variables using double curly brace syntax: {@code
 * {{variableName}}}. Variables are extracted using the regex pattern {@code /\{\{(\w+)\}\}/g}.
 *
 * @see com.locallab.model.Experiment
 */
@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "task_templates")
public class TaskTemplate {

    /**
     * Unique identifier for the task template.
     *
     * <p>Auto-generated by the database upon creation using identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Short, descriptive name for the task template.
     *
     * <p>Used for identification and selection in the UI. Should be concise but descriptive enough
     * to distinguish from other templates.
     *
     * <p>Examples: "Code Review Task", "Summarisation Task", "Translation Task"
     */
    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name must not exceed 100 characters")
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Detailed description of what this task evaluates or accomplishes.
     *
     * <p>Provides context about the purpose of the task template. Stored as a LOB to support
     * lengthy descriptions. This field is optional.
     */
    @Lob
    @Column(columnDefinition = "CLOB")
    private String description;

    /**
     * The main prompt template with optional variable placeholders.
     *
     * <p>Contains the prompt text sent to the LLM, potentially with {@code {{variable}}}
     * placeholders that are resolved at experiment execution time. Stored as a LOB to support
     * lengthy prompts.
     *
     * <p>Example: {@code "Review the following code:\n\n{{code}}\n\nProvide feedback on..."}
     */
    @Lob
    @NotBlank(message = "Prompt template is required")
    @Column(nullable = false, columnDefinition = "CLOB")
    private String promptTemplate;

    /**
     * Comma-separated list of tags for categorisation and filtering.
     *
     * <p>Tags enable organisation and filtering of templates in the UI. Multiple tags should be
     * separated by commas without spaces.
     *
     * <p>Example: {@code "code,review,quality"}
     */
    @Size(max = 500, message = "Tags must not exceed 500 characters")
    @Column(length = 500)
    private String tags;

    /**
     * Optional notes describing evaluation criteria or assessment guidelines.
     *
     * <p>Provides human reference notes for how to evaluate model outputs. Useful for maintaining
     * consistent evaluation standards across experiments. Stored as a LOB to support lengthy notes.
     *
     * <p>Example: {@code "Look for correctness, style, and performance improvements"}
     */
    @Lob
    @Column(columnDefinition = "CLOB")
    private String evaluationNotes;

    /**
     * Timestamp when this task template was created.
     *
     * <p>Automatically set by Hibernate on entity creation. Cannot be updated after creation.
     */
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * List of experiments that use this task template.
     *
     * <p>A TaskTemplate can be used by many Experiments. When a TaskTemplate is deleted, all
     * associated Experiments are also deleted (cascade). Orphan Experiments (those whose
     * TaskTemplate reference is removed) are automatically deleted.
     *
     * <p>The relationship is mapped by the {@code taskTemplate} field in the Experiment entity.
     */
    @Builder.Default
    @OneToMany(mappedBy = "taskTemplate", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Experiment> experiments = new ArrayList<>();
}
