package com.locallab.dto.response;

import java.time.LocalDateTime;
import java.util.List;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.locallab.dto.RetrievedChunk;
import com.locallab.model.ExperimentRun;
import com.locallab.model.enums.RunStatus;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response DTO for ExperimentRun entities.
 *
 * <p>This class encapsulates all fields returned when retrieving experiment runs. It provides a
 * clean separation between the internal entity representation and the API response format.
 *
 * <p>Example JSON output:
 *
 * <pre>{@code
 * {
 *   "id": 1,
 *   "experimentId": 1,
 *   "modelName": "qwen2.5-coder:7b",
 *   "embeddingModel": { "id": 1, "name": "Nomic Embed Text" },
 *   "systemPrompt": { "id": 1, "alias": "code-assistant" },
 *   "iteration": 1,
 *   "config": "{ ... }",
 *   "status": "SUCCESS",
 *   "output": "The code looks well-structured...",
 *   "durationMs": 2500,
 *   "tokensPerSecond": 45.5,
 *   "timeToFirstTokenMs": 120,
 *   "retrievedChunks": [ ... ],
 *   "errorMessage": null,
 *   "timestamp": "2025-11-27T10:05:00"
 * }
 * }</pre>
 *
 * @author William Stephen
 * @see ExperimentRun
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExperimentRunResponse {

    /** Unique identifier for the experiment run. */
    private Long id;

    /** The identifier of the parent experiment. */
    private Long experimentId;

    /** The name of the Ollama model used for this run. */
    private String modelName;

    /** Summary of the embedding model used (if applicable). */
    private EmbeddingModelSummary embeddingModel;

    /** Summary of the system prompt used (if applicable). */
    private SystemPromptSummary systemPrompt;

    /** The iteration number within the experiment (1-indexed). */
    private Integer iteration;

    /** JSON configuration string containing the exact parameters used. */
    private String config;

    /** Current status of the run. */
    private RunStatus status;

    /** The complete output generated by the model. */
    private String output;

    /** Total generation time in milliseconds. */
    private Long durationMs;

    /** Throughput metric: tokens generated per second. */
    private Double tokensPerSecond;

    /** Time to first token in milliseconds. */
    private Long timeToFirstTokenMs;

    /** List of retrieved document chunks for RAG runs. */
    private List<RetrievedChunk> retrievedChunks;

    /** Error message if the run failed. */
    private String errorMessage;

    /** Timestamp when this run was executed. */
    private LocalDateTime timestamp;

    /** Shared ObjectMapper instance for JSON parsing. */
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    /**
     * Creates an ExperimentRunResponse from an ExperimentRun entity.
     *
     * <p>This factory method provides a convenient way to convert entity objects to response DTOs.
     * It handles parsing of JSON fields and conversion of related entities to summary DTOs.
     *
     * @param run the experiment run entity to convert (must not be null)
     * @return a new ExperimentRunResponse containing all entity data
     * @throws IllegalArgumentException if run is null
     */
    public static ExperimentRunResponse fromEntity(ExperimentRun run) {
        if (run == null) {
            throw new IllegalArgumentException("ExperimentRun must not be null");
        }

        List<RetrievedChunk> chunks = parseRetrievedChunks(run.getRetrievedChunks());

        return ExperimentRunResponse.builder()
                .id(run.getId())
                .experimentId(run.getExperiment() != null ? run.getExperiment().getId() : null)
                .modelName(run.getModelName())
                .embeddingModel(EmbeddingModelSummary.fromEntity(run.getEmbeddingModel()))
                .systemPrompt(SystemPromptSummary.fromEntity(run.getSystemPrompt()))
                .iteration(run.getIteration())
                .config(run.getConfig())
                .status(run.getStatus())
                .output(run.getOutput())
                .durationMs(run.getDurationMs())
                .tokensPerSecond(run.getTokensPerSecond())
                .timeToFirstTokenMs(run.getTimeToFirstTokenMs())
                .retrievedChunks(chunks)
                .errorMessage(run.getErrorMessage())
                .timestamp(run.getTimestamp())
                .build();
    }

    /**
     * Parses the retrieved chunks JSON string into a list of RetrievedChunk objects.
     *
     * @param chunksJson the JSON string to parse (may be null or empty)
     * @return a list of RetrievedChunk objects, or null if the input is null or empty
     */
    private static List<RetrievedChunk> parseRetrievedChunks(String chunksJson) {
        if (chunksJson == null || chunksJson.isEmpty()) {
            return null;
        }
        try {
            return OBJECT_MAPPER.readValue(
                    chunksJson, new TypeReference<List<RetrievedChunk>>() {});
        } catch (JsonProcessingException e) {
            // Return null if JSON cannot be parsed (data integrity issue)
            return null;
        }
    }
}
